/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedClassRouteImport } from './routes/_authenticated/class'
import { Route as AuthenticatedConstellationTestRouteImport } from './routes/_authenticated/constellation-test'
import { Route as AuthenticatedNoticeRouteImport } from './routes/_authenticated/notice'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedSchoolRouteImport } from './routes/_authenticated/school'
import { Route as AuthenticatedThisWeekRouteImport } from './routes/_authenticated/this-week'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminSchoolsRouteImport } from './routes/_authenticated/admin/schools'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin/teachers'
import { Route as AuthenticatedStudentStudentIdRouteImport } from './routes/_authenticated/student.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassRoute = AuthenticatedClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConstellationTestRoute =
  AuthenticatedConstellationTestRouteImport.update({
    id: '/constellation-test',
    path: '/constellation-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNoticeRoute = AuthenticatedNoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolRoute = AuthenticatedSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThisWeekRoute = AuthenticatedThisWeekRouteImport.update({
  id: '/this-week',
  path: '/this-week',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSchoolsRoute =
  AuthenticatedAdminSchoolsRouteImport.update({
    id: '/schools',
    path: '/schools',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedStudentStudentIdRoute =
  AuthenticatedStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/preview': typeof PreviewRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/class': typeof AuthenticatedClassRoute
  '/constellation-test': typeof AuthenticatedConstellationTestRoute
  '/notice': typeof AuthenticatedNoticeRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/school': typeof AuthenticatedSchoolRoute
  '/this-week': typeof AuthenticatedThisWeekRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/student/$studentId': typeof AuthenticatedStudentStudentIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/preview': typeof PreviewRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/class': typeof AuthenticatedClassRoute
  '/constellation-test': typeof AuthenticatedConstellationTestRoute
  '/notice': typeof AuthenticatedNoticeRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/school': typeof AuthenticatedSchoolRoute
  '/this-week': typeof AuthenticatedThisWeekRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/student/$studentId': typeof AuthenticatedStudentStudentIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/preview': typeof PreviewRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/class': typeof AuthenticatedClassRoute
  '/_authenticated/constellation-test': typeof AuthenticatedConstellationTestRoute
  '/_authenticated/notice': typeof AuthenticatedNoticeRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/school': typeof AuthenticatedSchoolRoute
  '/_authenticated/this-week': typeof AuthenticatedThisWeekRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/schools': typeof AuthenticatedAdminSchoolsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/student/$studentId': typeof AuthenticatedStudentStudentIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/preview'
    | '/admin'
    | '/attendance'
    | '/class'
    | '/constellation-test'
    | '/notice'
    | '/roster'
    | '/school'
    | '/this-week'
    | '/admin/audit'
    | '/admin/schools'
    | '/admin/students'
    | '/admin/teachers'
    | '/student/$studentId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/preview'
    | '/attendance'
    | '/class'
    | '/constellation-test'
    | '/notice'
    | '/roster'
    | '/school'
    | '/this-week'
    | '/admin/audit'
    | '/admin/schools'
    | '/admin/students'
    | '/admin/teachers'
    | '/student/$studentId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/preview'
    | '/_authenticated/admin'
    | '/_authenticated/attendance'
    | '/_authenticated/class'
    | '/_authenticated/constellation-test'
    | '/_authenticated/notice'
    | '/_authenticated/roster'
    | '/_authenticated/school'
    | '/_authenticated/this-week'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/schools'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/student/$studentId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PreviewRoute: typeof PreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/class': {
      id: '/_authenticated/class'
      path: '/class'
      fullPath: '/class'
      preLoaderRoute: typeof AuthenticatedClassRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/constellation-test': {
      id: '/_authenticated/constellation-test'
      path: '/constellation-test'
      fullPath: '/constellation-test'
      preLoaderRoute: typeof AuthenticatedConstellationTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notice': {
      id: '/_authenticated/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof AuthenticatedNoticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school': {
      id: '/_authenticated/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof AuthenticatedSchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/this-week': {
      id: '/_authenticated/this-week'
      path: '/this-week'
      fullPath: '/this-week'
      preLoaderRoute: typeof AuthenticatedThisWeekRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/schools': {
      id: '/_authenticated/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AuthenticatedAdminSchoolsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/student/$studentId': {
      id: '/_authenticated/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/student/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminSchoolsRoute: typeof AuthenticatedAdminSchoolsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminSchoolsRoute: AuthenticatedAdminSchoolsRoute,
    AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
    AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedClassRoute: typeof AuthenticatedClassRoute
  AuthenticatedConstellationTestRoute: typeof AuthenticatedConstellationTestRoute
  AuthenticatedNoticeRoute: typeof AuthenticatedNoticeRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedSchoolRoute: typeof AuthenticatedSchoolRoute
  AuthenticatedThisWeekRoute: typeof AuthenticatedThisWeekRoute
  AuthenticatedStudentStudentIdRoute: typeof AuthenticatedStudentStudentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedClassRoute: AuthenticatedClassRoute,
  AuthenticatedConstellationTestRoute: AuthenticatedConstellationTestRoute,
  AuthenticatedNoticeRoute: AuthenticatedNoticeRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedSchoolRoute: AuthenticatedSchoolRoute,
  AuthenticatedThisWeekRoute: AuthenticatedThisWeekRoute,
  AuthenticatedStudentStudentIdRoute: AuthenticatedStudentStudentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PreviewRoute: PreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
